# Generated by Django 3.1.7 on 2021-04-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.PositiveBigIntegerField(default='2342'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pincode',
            field=models.PositiveIntegerField(default='234'),
        ),
    ]
