# Generated by Django 3.1.7 on 2021-04-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210402_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(default='as', max_length=400),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='jai@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.PositiveBigIntegerField(default='2'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pincode',
            field=models.PositiveIntegerField(default='234'),
        ),
    ]
