# Generated by Django 3.1.7 on 2021-04-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210402_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.PositiveBigIntegerField(default='223'),
        ),
    ]
