# Generated by Django 3.1.7 on 2021-04-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_patient_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
    ]
