# Generated by Django 3.1.7 on 2021-04-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210404_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='slot',
            field=models.JSONField(default={}),
        ),
    ]
