# Generated by Django 3.1.7 on 2021-04-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_patient_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='slot',
            field=models.JSONField(default=dict),
        ),
    ]
