export const SET_DATE= 'SET_DATE';
export const SET_TIME= 'SET_TIME';
export const SET_TIME_SLOT= 'SET_TIME_SLOT';
export const SET_CURRENT_USER_BOOKINGS= 'SET_CURRENT_USER_BOOKINGS';
export const SET_CURRENT_DATE_APPOINTMENTS= 'SET_CURRENT_DATE_APPOINTMENTS';
export const SET_USER_LOG_IN= 'SET_USER_LOG_IN';
export const SET_USER_LOG_OUT= 'SET_USER_LOG_OUT';
export const SET_STAFF_STATUS= 'SET_STAFF_STATUS';