# Generated by Django 3.1.7 on 2021-04-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Patient',
        ),
    ]
