# Generated by Django 3.1.7 on 2021-04-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_auto_20210402_1417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
